package codegen

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

const (
	generatedHeader  = "// Code generated by c2go; DO NOT EDIT."
	textflagHeader   = "#include \"textflag.h\""
	defaultFuncFlags = "NOSPLIT|NOFRAME"
)

type asmFunc struct {
	name     string
	comments []string
	body     []string
}

type asmData struct {
	name   string
	values []asmDataValue
}

type asmDataValue struct {
	size  int
	value string
}

type asmFileBuilder struct {
	fileComments    []string
	pendingComments []string
	data            []asmData
	currentData     asmData
	funcs           []asmFunc
	current         *asmFunc
	pendingSymbol   string
	pendingLabel    string
	ended           bool
}

func RenderAsmFile(src string) (string, error) {
	b := asmFileBuilder{}
	for _, raw := range strings.Split(normalizeNewlines(src), "\n") {
		if err := b.addLine(strings.TrimSpace(raw)); err != nil {
			return "", err
		}
	}
	b.finishData()
	b.finishFunc()
	if len(b.funcs) == 0 {
		return "", fmt.Errorf("no function labels found in translated asm")
	}
	return render(b.fileComments, b.data, b.funcs), nil
}

func (b *asmFileBuilder) addLine(line string) error {
	switch {
	case line == "":
		return nil
	case strings.HasPrefix(line, "PCALIGN ") && b.current == nil:
		b.pendingComments = append(b.pendingComments, "\t"+line)
		return nil
	case strings.HasPrefix(line, "//"):
		if symbol, ok := globlComment(line); ok {
			b.addGlobl(line, symbol)
			return nil
		}
		b.addComment(line)
		return nil
	}
	if label, ok := parseLabel(line); ok {
		b.addLabel(label)
		return nil
	}
	if value, size, ok := parseDataValue(line); ok {
		return b.addData(value, size)
	}
	return b.addInstruction(line)
}

func (b *asmFileBuilder) addGlobl(line, symbol string) {
	b.finishData()
	b.finishFunc()
	b.pendingSymbol = symbol
	b.pendingComments = append(b.pendingComments, line)
}

func (b *asmFileBuilder) addLabel(label string) {
	if label == b.pendingSymbol {
		b.startFunc(label)
		return
	}
	label = plan9LocalLabel(label)
	if b.current == nil || b.ended {
		b.finishData()
		b.pendingLabel = label
		return
	}
	b.current.body = append(b.current.body, label+":")
	b.ended = false
}

func (b *asmFileBuilder) addComment(line string) {
	if b.current != nil {
		b.current.body = append(b.current.body, "\t"+line)
		return
	}
	if _, ok := frameMarker(line); ok && b.pendingLabel != "" {
		b.startFunc(b.pendingLabel)
		b.current.body = append(b.current.body, "\t"+line)
		return
	}
	b.addPreambleComment(line)
}

func (b *asmFileBuilder) addPreambleComment(line string) {
	if b.pendingSymbol != "" || len(b.pendingComments) > 0 {
		b.pendingComments = append(b.pendingComments, line)
		return
	}
	b.fileComments = append(b.fileComments, line)
}

func (b *asmFileBuilder) addInstruction(line string) error {
	b.resolvePendingLabel()
	if b.current == nil {
		return fmt.Errorf("encountered non-function line before any function label: %q", line)
	}
	line = plan9LocalRefs(line)
	b.current.body = append(b.current.body, "\t"+line)
	b.ended = line == "RET" || strings.HasPrefix(line, "JMP ")
	return nil
}

func (b *asmFileBuilder) addData(value string, size int) error {
	if b.current != nil {
		if !b.ended {
			return fmt.Errorf("encountered data before function end: %q", value)
		}
		b.finishFunc()
	}
	if b.currentData.name == "" {
		if b.pendingLabel == "" {
			return fmt.Errorf("encountered data before any data label")
		}
		b.currentData.name = plan9LocalLabel(b.pendingLabel)
		b.pendingLabel = ""
	}
	b.currentData.values = append(b.currentData.values, asmDataValue{size: size, value: value})
	return nil
}

func (b *asmFileBuilder) resolvePendingLabel() {
	if b.pendingLabel == "" {
		return
	}
	if b.current == nil || looksLikeFunctionLabel(b.pendingLabel) {
		b.startFunc(b.pendingLabel)
		return
	}
	b.current.body = append(b.current.body, b.pendingLabel+":")
	b.pendingLabel = ""
}

func (b *asmFileBuilder) startFunc(label string) {
	b.finishData()
	b.finishFunc()
	b.current = &asmFunc{name: withSB(label), comments: b.pendingComments}
	b.pendingComments = nil
	b.pendingSymbol = ""
	b.pendingLabel = ""
}

func (b *asmFileBuilder) finishFunc() {
	if b.current == nil {
		return
	}
	if !b.ended {
		b.current.body = append(b.current.body, "\tRET")
	}
	b.funcs = append(b.funcs, *b.current)
	b.current = nil
	b.ended = false
}

func (b *asmFileBuilder) finishData() {
	if b.currentData.name == "" {
		return
	}
	b.data = append(b.data, b.currentData)
	b.currentData = asmData{}
}

func render(fileComments []string, data []asmData, funcs []asmFunc) string {
	var out []string
	out = append(out, generatedHeader, textflagHeader)
	out = append(out, fileComments...)
	out = append(out, "")
	for _, datum := range data {
		offset := 0
		for _, item := range datum.values {
			out = append(out, fmt.Sprintf("DATA %s+%d(SB)/%d, $%s", datum.name, offset, item.size, item.value))
			offset += item.size
		}
		out = append(out, fmt.Sprintf("GLOBL %s(SB), RODATA|NOPTR, $%d", datum.name, offset), "")
	}
	for i, fn := range funcs {
		if i > 0 {
			out = append(out, "")
		}
		body, frame := frameFromMarkers(fn.body)
		flags := defaultFuncFlags
		frameText := "$0"
		if frame > 0 {
			flags = "NOSPLIT"
			frameText = fmt.Sprintf("$%d-0", frame)
		}
		out = append(out, fn.comments...)
		out = append(out, fmt.Sprintf("TEXT %s, %s, %s", fn.name, flags, frameText))
		out = append(out, body...)
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n") + "\n"
}

func frameFromMarkers(body []string) ([]string, int) {
	out := make([]string, 0, len(body))
	frame := 0
	for _, line := range body {
		if size, ok := frameMarker(line); ok {
			if size > frame {
				frame = size
			}
			continue
		}
		out = append(out, line)
	}
	return out, frame
}

func frameMarker(line string) (int, bool) {
	fields := commentFields(line)
	if len(fields) == 3 && fields[0] == "c2go:" && fields[1] == "frame" {
		n, err := strconv.Atoi(fields[2])
		return n, err == nil && n > 0
	}
	return 0, false
}

func withSB(name string) string {
	name = strings.TrimSpace(name)
	if name == "" || strings.Contains(name, "(SB)") {
		return name
	}
	return name + "(SB)"
}

func commentFields(line string) []string {
	line = strings.TrimSpace(line)
	if !strings.HasPrefix(line, "//") {
		return nil
	}
	return strings.Fields(strings.TrimSpace(strings.TrimPrefix(line, "//")))
}

func globlComment(line string) (string, bool) {
	fields := commentFields(line)
	if len(fields) >= 2 && (fields[0] == ".globl" || fields[0] == ".global") {
		return fields[1], true
	}
	return "", false
}

func normalizeNewlines(src string) string {
	return strings.ReplaceAll(strings.ReplaceAll(src, "\r\n", "\n"), "\r", "\n")
}

func parseLabel(line string) (string, bool) {
	if !strings.HasSuffix(line, ":") {
		return "", false
	}
	label := strings.TrimSpace(strings.TrimSuffix(line, ":"))
	if label == "" || strings.ContainsAny(label, " \t") {
		return "", false
	}
	return label, true
}

func parseDataValue(line string) (string, int, bool) {
	fields := strings.Fields(line)
	if len(fields) < 2 {
		return "", 0, false
	}
	size, ok := dataSizes[strings.ToLower(fields[0])]
	if !ok {
		return "", 0, false
	}
	return strings.TrimSpace(strings.TrimPrefix(line, fields[0])), size, true
}

func looksLikeFunctionLabel(label string) bool {
	return label != "" && !strings.HasPrefix(label, ".L") && !strings.HasPrefix(label, "L")
}

var dataSizes = map[string]int{
	".byte":  1,
	".short": 2,
	".word":  2,
	".long":  4,
	".quad":  8,
	".xword": 8,
}

var localLabelRefRE = regexp.MustCompile(`(^|[^A-Za-z0-9_])\.L([A-Za-z0-9_]+)`)
var dottedSBRefRE = regexp.MustCompile(`\b[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z0-9_.$]*(?:\+[-0-9]+)?\(SB\)`)

func plan9LocalLabel(label string) string {
	return sanitizeAsmSymbol(strings.TrimPrefix(label, "."))
}

func plan9LocalRefs(line string) string {
	line = localLabelRefRE.ReplaceAllString(line, `${1}L${2}`)
	return dottedSBRefRE.ReplaceAllStringFunc(line, func(ref string) string {
		return strings.ReplaceAll(ref, ".", "_")
	})
}

func sanitizeAsmSymbol(symbol string) string {
	return strings.ReplaceAll(symbol, ".", "_")
}
