package codegen

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

const (
	generatedHeader  = "// Code generated by c2go; DO NOT EDIT."
	textflagHeader   = "#include \"textflag.h\""
	defaultFuncFlags = "NOSPLIT|NOFRAME"
	defaultFuncFrame = "$0"
)

type asmFunc struct {
	name     string
	comments []string
	body     []string
}

type asmData struct {
	name   string
	values []string
}

type asmFileBuilder struct {
	fileComments    []string
	pendingComments []string
	data            []asmData
	currentData     asmData
	funcs           []asmFunc
	current         *asmFunc
	pendingSymbol   string
	pendingLabel    string
	ended           bool
}

func RenderAsmFile(src string) (string, error) {
	b := asmFileBuilder{}
	for _, raw := range strings.Split(normalizeNewlines(src), "\n") {
		if err := b.addLine(strings.TrimSpace(raw)); err != nil {
			return "", err
		}
	}
	b.finishData()
	b.finishFunc()
	if len(b.funcs) == 0 {
		return "", fmt.Errorf("no function labels found in translated asm")
	}
	return render(b.fileComments, b.data, b.funcs), nil
}

func (b *asmFileBuilder) addLine(line string) error {
	if line == "" {
		b.addBlank()
		return nil
	}
	if isGloblComment(line) {
		b.addGlobl(line)
		return nil
	}
	if strings.HasPrefix(line, "PCALIGN ") && b.current == nil {
		b.pendingComments = append(b.pendingComments, "\t"+line)
		return nil
	}
	if strings.HasPrefix(line, "//") {
		b.addComment(line)
		return nil
	}
	if label, ok := parseLabel(line); ok {
		b.addLabel(label)
		return nil
	}
	if value, size, ok := parseDataValue(line); ok {
		return b.addData(value, size)
	}
	return b.addInstruction(line)
}

func (b *asmFileBuilder) addBlank() {
	// Compiler asm often contains decorative spacing. The generated Plan 9 file
	// keeps only structural spacing emitted by render().
}

func (b *asmFileBuilder) addGlobl(line string) {
	b.finishData()
	b.finishFunc()
	b.pendingSymbol = globlSymbol(line)
	b.pendingComments = append(b.pendingComments, line)
}

func (b *asmFileBuilder) addLabel(label string) {
	if b.current == nil {
		b.finishData()
		b.pendingLabel = label
		return
	}
	if label == b.pendingSymbol || (b.ended && looksLikeFunctionLabel(label)) {
		b.startFunc(label)
		return
	}
	b.current.body = append(b.current.body, plan9LocalLabel(label)+":")
	b.ended = false
}

func (b *asmFileBuilder) addComment(line string) {
	switch {
	case b.current == nil && b.pendingLabel != "" && isFrameMarker(line):
		b.startFunc(b.pendingLabel)
		b.current.body = append(b.current.body, "\t"+line)
	case b.current == nil:
		b.addPreambleComment(line)
	default:
		b.current.body = append(b.current.body, "\t"+line)
	}
}

func (b *asmFileBuilder) addPreambleComment(line string) {
	if b.pendingSymbol != "" || len(b.pendingComments) > 0 {
		b.pendingComments = append(b.pendingComments, line)
		return
	}
	b.fileComments = append(b.fileComments, line)
}

func (b *asmFileBuilder) addInstruction(line string) error {
	if b.current == nil {
		if b.pendingLabel == "" {
			return fmt.Errorf("encountered non-function line before any function label: %q", line)
		}
		b.startFunc(b.pendingLabel)
	}
	line = plan9LocalRefs(line)
	b.current.body = append(b.current.body, "\t"+line)
	b.ended = line == "RET"
	return nil
}

func (b *asmFileBuilder) addData(value string, size int) error {
	if b.current != nil {
		return b.addInstruction(fmt.Sprintf(".%s %s", dataDirective(size), value))
	}
	return b.addDataSized(value, size)
}

func (b *asmFileBuilder) addDataSized(value string, size int) error {
	if b.currentData.name == "" {
		if b.pendingLabel == "" {
			return fmt.Errorf("encountered data before any data label")
		}
		b.currentData.name = plan9LocalLabel(b.pendingLabel)
		b.pendingLabel = ""
	}
	b.currentData.values = append(b.currentData.values, fmt.Sprintf("%d:%s", size, value))
	return nil
}

func (b *asmFileBuilder) startFunc(label string) {
	b.finishData()
	b.finishFunc()
	b.current = &asmFunc{name: withSB(label), comments: append([]string(nil), b.pendingComments...)}
	b.pendingComments = nil
	b.pendingSymbol = ""
	b.pendingLabel = ""
}

func (b *asmFileBuilder) finishFunc() {
	if b.current != nil {
		if !b.ended {
			b.current.body = append(b.current.body, "\tRET")
		}
		b.funcs = append(b.funcs, *b.current)
		b.current = nil
		b.ended = false
	}
}

func (b *asmFileBuilder) finishData() {
	if b.currentData.name != "" {
		b.data = append(b.data, b.currentData)
		b.currentData = asmData{}
	}
}

func render(fileComments []string, data []asmData, funcs []asmFunc) string {
	var out []string
	out = append(out, generatedHeader, textflagHeader)
	out = append(out, fileComments...)
	out = append(out, "")
	for _, datum := range data {
		offset := 0
		for _, item := range datum.values {
			size, value := splitDataItem(item)
			out = append(out, fmt.Sprintf("DATA %s+%d(SB)/%d, $%s", datum.name, offset, size, value))
			offset += size
		}
		out = append(out, fmt.Sprintf("GLOBL %s(SB), RODATA|NOPTR, $%d", datum.name, dataSize(datum.values)), "")
	}
	for i, fn := range funcs {
		if i > 0 {
			out = append(out, "")
		}
		body, frame := frameFromMarkers(fn.body)
		flags := defaultFuncFlags
		if frame > 0 {
			flags = strings.ReplaceAll(flags, "|NOFRAME", "")
		}
		frameText := "$0"
		if frame > 0 {
			frameText = fmt.Sprintf("$%d-0", frame)
		}
		out = append(out, fn.comments...)
		out = append(out, fmt.Sprintf("TEXT %s, %s, %s", fn.name, flags, frameText))
		out = append(out, body...)
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n") + "\n"
}

func frameFromMarkers(body []string) ([]string, int) {
	out := make([]string, 0, len(body))
	frame := 0
	for _, line := range body {
		if size, ok := frameMarker(line); ok {
			if size > frame {
				frame = size
			}
			continue
		}
		out = append(out, line)
	}
	return out, frame
}

func frameMarker(line string) (int, bool) {
	fields := strings.Fields(strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "//")))
	if len(fields) == 3 && fields[0] == "c2go:" && fields[1] == "frame" {
		n, err := strconv.Atoi(fields[2])
		return n, err == nil && n > 0
	}
	return 0, false
}

func isFrameMarker(line string) bool {
	_, ok := frameMarker(line)
	return ok
}

func dataSize(values []string) int {
	n := 0
	for _, value := range values {
		size, _ := splitDataItem(value)
		n += size
	}
	return n
}

func splitDataItem(item string) (int, string) {
	sizeText, value, ok := strings.Cut(item, ":")
	if !ok {
		return 8, item
	}
	switch sizeText {
	case "1":
		return 1, value
	case "2":
		return 2, value
	case "4":
		return 4, value
	default:
		return 8, value
	}
}

func withSB(name string) string {
	name = strings.TrimSpace(name)
	if name == "" || strings.Contains(name, "(SB)") {
		return name
	}
	return name + "(SB)"
}

func isGloblComment(line string) bool {
	if !strings.HasPrefix(line, "//") {
		return false
	}
	fields := strings.Fields(strings.TrimSpace(strings.TrimPrefix(line, "//")))
	return len(fields) >= 2 && (fields[0] == ".globl" || fields[0] == ".global")
}

func globlSymbol(line string) string {
	return strings.Fields(strings.TrimSpace(strings.TrimPrefix(line, "//")))[1]
}

func normalizeNewlines(src string) string {
	return strings.ReplaceAll(strings.ReplaceAll(src, "\r\n", "\n"), "\r", "\n")
}

func parseLabel(line string) (string, bool) {
	if !strings.HasSuffix(line, ":") {
		return "", false
	}
	label := strings.TrimSpace(strings.TrimSuffix(line, ":"))
	if label == "" || strings.ContainsAny(label, " \t") {
		return "", false
	}
	return label, true
}

func parseDataValue(line string) (string, int, bool) {
	fields := strings.Fields(line)
	if len(fields) < 2 {
		return "", 0, false
	}
	size := 0
	switch strings.ToLower(fields[0]) {
	case ".byte":
		size = 1
	case ".short", ".word":
		size = 2
	case ".long":
		size = 4
	case ".quad", ".xword":
		size = 8
	default:
		return "", 0, false
	}
	return strings.TrimSpace(strings.TrimPrefix(line, fields[0])), size, true
}

func dataDirective(size int) string {
	switch size {
	case 1:
		return "byte"
	case 2:
		return "short"
	case 4:
		return "long"
	case 8:
		return "quad"
	default:
		panic(fmt.Sprintf("invalid data directive size %d", size))
	}
}

func looksLikeFunctionLabel(label string) bool {
	return label != "" && !strings.HasPrefix(label, ".L") && !strings.HasPrefix(label, "L")
}

var localLabelRefRE = regexp.MustCompile(`(^|[^A-Za-z0-9_])\.L([A-Za-z0-9_]+)`)
var dottedSBRefRE = regexp.MustCompile(`\b[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z0-9_.$]*(?:\+[-0-9]+)?\(SB\)`)

func plan9LocalLabel(label string) string {
	return sanitizeAsmSymbol(strings.TrimPrefix(label, "."))
}

func plan9LocalRefs(line string) string {
	line = localLabelRefRE.ReplaceAllString(line, `${1}L${2}`)
	return dottedSBRefRE.ReplaceAllStringFunc(line, func(ref string) string {
		return strings.ReplaceAll(ref, ".", "_")
	})
}

func sanitizeAsmSymbol(symbol string) string {
	return strings.ReplaceAll(symbol, ".", "_")
}
