package codegen

import (
	"fmt"
	"regexp"
	"strings"
)

const (
	generatedHeader  = "// Code generated by c2go; DO NOT EDIT."
	textflagHeader   = "#include \"textflag.h\""
	defaultFuncFlags = "NOSPLIT|NOFRAME"
	defaultFuncFrame = "$0"
)

type asmFunc struct {
	name     string
	comments []string
	body     []string
}

type asmData struct {
	name   string
	values []string
}

type asmFileBuilder struct {
	fileComments    []string
	pendingComments []string
	data            []asmData
	currentData     asmData
	funcs           []asmFunc
	current         *asmFunc
	pendingSymbol   string
	pendingLabel    string
	ended           bool
}

func RenderAsmFile(src string) (string, error) {
	b := asmFileBuilder{}
	for _, raw := range strings.Split(normalizeNewlines(src), "\n") {
		if err := b.addLine(strings.TrimSpace(raw)); err != nil {
			return "", err
		}
	}
	b.finishData()
	b.finishFunc()
	if len(b.funcs) == 0 {
		return "", fmt.Errorf("no function labels found in translated asm")
	}
	return render(b.fileComments, b.data, b.funcs), nil
}

func (b *asmFileBuilder) addLine(line string) error {
	if line == "" {
		b.addBlank()
		return nil
	}
	if isGloblComment(line) {
		b.addGlobl(line)
		return nil
	}
	if strings.HasPrefix(line, "//") {
		b.addComment(line)
		return nil
	}
	if label, ok := parseLabel(line); ok {
		b.addLabel(label)
		return nil
	}
	if value, ok := parseQuad(line); ok {
		return b.addData(value)
	}
	if value, ok := parseLong(line); ok {
		return b.addData32(value)
	}
	return b.addInstruction(line)
}

func (b *asmFileBuilder) addBlank() {
	// Compiler asm often contains decorative spacing. The generated Plan 9 file
	// keeps only structural spacing emitted by render().
}

func (b *asmFileBuilder) addGlobl(line string) {
	b.finishData()
	b.finishFunc()
	b.pendingSymbol = globlSymbol(line)
	b.pendingComments = append(b.pendingComments, line)
}

func (b *asmFileBuilder) addLabel(label string) {
	if b.current == nil {
		b.finishData()
		b.pendingLabel = label
		return
	}
	if label == b.pendingSymbol || (b.ended && looksLikeFunctionLabel(label)) {
		b.startFunc(label)
		return
	}
	b.current.body = append(b.current.body, plan9LocalLabel(label)+":")
	b.ended = false
}

func (b *asmFileBuilder) addComment(line string) {
	switch {
	case b.current == nil:
		b.addPreambleComment(line)
	case b.ended:
		b.finishFunc()
		b.pendingComments = append(b.pendingComments, line)
	default:
		b.current.body = append(b.current.body, "\t"+line)
	}
}

func (b *asmFileBuilder) addPreambleComment(line string) {
	if b.pendingSymbol != "" || len(b.pendingComments) > 0 {
		b.pendingComments = append(b.pendingComments, line)
		return
	}
	b.fileComments = append(b.fileComments, line)
}

func (b *asmFileBuilder) addInstruction(line string) error {
	if b.current == nil {
		if b.pendingLabel == "" {
			return fmt.Errorf("encountered non-function line before any function label: %q", line)
		}
		b.startFunc(b.pendingLabel)
	}
	line = plan9LocalRefs(line)
	b.current.body = append(b.current.body, "\t"+line)
	b.ended = line == "RET"
	return nil
}

func (b *asmFileBuilder) addData(value string) error {
	if b.current != nil {
		return b.addInstruction(".quad " + value)
	}
	return b.addDataSized(value, 8)
}

func (b *asmFileBuilder) addData32(value string) error {
	if b.current != nil {
		return b.addInstruction(".long " + value)
	}
	return b.addDataSized(value, 4)
}

func (b *asmFileBuilder) addDataSized(value string, size int) error {
	if b.currentData.name == "" {
		if b.pendingLabel == "" {
			return fmt.Errorf("encountered data before any data label")
		}
		b.currentData.name = plan9LocalLabel(b.pendingLabel)
		b.pendingLabel = ""
	}
	if size == 4 {
		b.currentData.values = append(b.currentData.values, ".long "+value)
	} else {
		b.currentData.values = append(b.currentData.values, value)
	}
	return nil
}

func (b *asmFileBuilder) startFunc(label string) {
	b.finishData()
	b.finishFunc()
	b.current = &asmFunc{name: withSB(label), comments: append([]string(nil), b.pendingComments...)}
	b.pendingComments = nil
	b.pendingSymbol = ""
	b.pendingLabel = ""
}

func (b *asmFileBuilder) finishFunc() {
	if b.current != nil {
		b.funcs = append(b.funcs, *b.current)
		b.current = nil
		b.ended = false
	}
}

func (b *asmFileBuilder) finishData() {
	if b.currentData.name != "" {
		b.data = append(b.data, b.currentData)
		b.currentData = asmData{}
	}
}

func render(fileComments []string, data []asmData, funcs []asmFunc) string {
	var out []string
	out = append(out, generatedHeader, textflagHeader)
	out = append(out, fileComments...)
	out = append(out, "")
	for _, datum := range data {
		offset := 0
		for _, value := range datum.values {
			if strings.HasPrefix(value, ".long ") {
				out = append(out, fmt.Sprintf("DATA %s+%d(SB)/4, $%s", datum.name, offset, strings.TrimPrefix(value, ".long ")))
				offset += 4
				continue
			}
			out = append(out, fmt.Sprintf("DATA %s+%d(SB)/8, $%s", datum.name, offset, value))
			offset += 8
		}
		out = append(out, fmt.Sprintf("GLOBL %s(SB), RODATA|NOPTR, $%d", datum.name, dataSize(datum.values)), "")
	}
	for i, fn := range funcs {
		if i > 0 {
			out = append(out, "")
		}
		body, frame := rewritePushPopFrame(fn.body)
		flags := defaultFuncFlags
		if frame > 0 {
			flags = strings.ReplaceAll(flags, "|NOFRAME", "")
		}
		out = append(out, fn.comments...)
		out = append(out, fmt.Sprintf("TEXT %s, %s, $%d", fn.name, flags, frame))
		out = append(out, body...)
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n") + "\n"
}

func rewritePushPopFrame(body []string) ([]string, int) {
	var regs []string
	for _, line := range body {
		reg, ok := pushReg(line)
		if !ok {
			break
		}
		regs = append(regs, reg)
	}
	if len(regs) == 0 {
		return body, 0
	}
	slots := make(map[string]int, len(regs))
	out := make([]string, 0, len(body))
	for i, reg := range regs {
		slots[reg] = i * 8
		out = append(out, fmt.Sprintf("\tMOVQ %s, %d(SP)", reg, i*8))
	}
	for _, line := range body[len(regs):] {
		if reg, ok := popReg(line); ok {
			if offset, ok := slots[reg]; ok {
				out = append(out, fmt.Sprintf("\tMOVQ %d(SP), %s", offset, reg))
				continue
			}
		}
		out = append(out, line)
	}
	return out, len(regs) * 8
}

func pushReg(line string) (string, bool) {
	fields := strings.Fields(strings.TrimSpace(line))
	if len(fields) == 2 && fields[0] == "PUSHQ" {
		return fields[1], true
	}
	return "", false
}

func popReg(line string) (string, bool) {
	fields := strings.Fields(strings.TrimSpace(line))
	if len(fields) == 2 && fields[0] == "POPQ" {
		return fields[1], true
	}
	return "", false
}

func dataSize(values []string) int {
	n := 0
	for _, value := range values {
		if strings.HasPrefix(value, ".long ") {
			n += 4
		} else {
			n += 8
		}
	}
	return n
}

func withSB(name string) string {
	name = strings.TrimSpace(name)
	if name == "" || strings.Contains(name, "(SB)") {
		return name
	}
	return name + "(SB)"
}

func isGloblComment(line string) bool {
	if !strings.HasPrefix(line, "//") {
		return false
	}
	fields := strings.Fields(strings.TrimSpace(strings.TrimPrefix(line, "//")))
	return len(fields) >= 2 && (fields[0] == ".globl" || fields[0] == ".global")
}

func globlSymbol(line string) string {
	return strings.Fields(strings.TrimSpace(strings.TrimPrefix(line, "//")))[1]
}

func normalizeNewlines(src string) string {
	return strings.ReplaceAll(strings.ReplaceAll(src, "\r\n", "\n"), "\r", "\n")
}

func parseLabel(line string) (string, bool) {
	if !strings.HasSuffix(line, ":") {
		return "", false
	}
	label := strings.TrimSpace(strings.TrimSuffix(line, ":"))
	if label == "" || strings.ContainsAny(label, " \t") {
		return "", false
	}
	return label, true
}

func parseQuad(line string) (string, bool) {
	fields := strings.Fields(line)
	if len(fields) < 2 || strings.ToLower(fields[0]) != ".quad" {
		return "", false
	}
	return strings.TrimSpace(strings.TrimPrefix(line, fields[0])), true
}

func parseLong(line string) (string, bool) {
	fields := strings.Fields(line)
	if len(fields) < 2 || strings.ToLower(fields[0]) != ".long" {
		return "", false
	}
	return strings.TrimSpace(strings.TrimPrefix(line, fields[0])), true
}

func looksLikeFunctionLabel(label string) bool {
	return label != "" && !strings.HasPrefix(label, ".L") && !strings.HasPrefix(label, "L")
}

var localLabelRefRE = regexp.MustCompile(`(^|[^A-Za-z0-9_])\.L([A-Za-z0-9_]+)`)
var dottedSBRefRE = regexp.MustCompile(`\b[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z0-9_.$]*(?:\+[-0-9]+)?\(SB\)`)

func plan9LocalLabel(label string) string {
	return sanitizeAsmSymbol(strings.TrimPrefix(label, "."))
}

func plan9LocalRefs(line string) string {
	line = localLabelRefRE.ReplaceAllString(line, `${1}L${2}`)
	return dottedSBRefRE.ReplaceAllStringFunc(line, func(ref string) string {
		return strings.ReplaceAll(ref, ".", "_")
	})
}

func sanitizeAsmSymbol(symbol string) string {
	return strings.ReplaceAll(symbol, ".", "_")
}
