package codegen

import (
	"strings"
	"testing"
)

func TestRenderAsmFileBuildsCompleteAsmFile(t *testing.T) {
	input := strings.TrimSpace(`
// .globl _add
_add:
LEAL (DI)(SI*1), AX
RET

// .globl _max2
_max2:
CMPL DI, SI
RET
`) + "\n"

	got, err := RenderAsmFile(input)
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	checks := []string{
		"// Code generated by c2go; DO NOT EDIT.",
		"#include \"textflag.h\"",
		"// .globl _add",
		"TEXT _add(SB), NOSPLIT|NOFRAME, $0",
		"\tLEAL (DI)(SI*1), AX",
		"TEXT _max2(SB), NOSPLIT|NOFRAME, $0",
		"\tCMPL DI, SI",
	}
	for _, want := range checks {
		if !strings.Contains(got, want) {
			t.Fatalf("output missing %q\n%s", want, got)
		}
	}
	if strings.Contains(got, "_add:\n") {
		t.Fatalf("function entry label should be replaced by TEXT\n%s", got)
	}
	if strings.Contains(got, "\n\n\n") {
		t.Fatalf("output should not contain repeated blank lines\n%s", got)
	}
}

func TestRenderAsmFileSingleLabelWithoutGlobl(t *testing.T) {
	got, err := RenderAsmFile("main:\nMOVQ SP, BP\nRET\n")
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	if !strings.Contains(got, "TEXT main(SB), NOSPLIT|NOFRAME, $0") {
		t.Fatalf("output missing TEXT header\n%s", got)
	}
	if strings.Contains(got, "main:\n") {
		t.Fatalf("function label should be consumed into TEXT\n%s", got)
	}
}

func TestRenderAsmFileKeepsPreambleCommentsWithNextFunction(t *testing.T) {
	input := strings.TrimSpace(`
// .globl _add
// .p2align 4, 0x90
_add:
RET

// .globl _sub
// .type _sub,@function
_sub:
RET
`) + "\n"

	got, err := RenderAsmFile(input)
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	checks := []string{
		"// .globl _add\n// .p2align 4, 0x90\nTEXT _add(SB), NOSPLIT|NOFRAME, $0",
		"// .globl _sub\n// .type _sub,@function\nTEXT _sub(SB), NOSPLIT|NOFRAME, $0",
	}
	for _, want := range checks {
		if !strings.Contains(got, want) {
			t.Fatalf("output missing %q\n%s", want, got)
		}
	}
	if strings.Contains(got, "\t// .type _sub,@function") {
		t.Fatalf("next-function preamble comment should not be appended to previous body\n%s", got)
	}
}

func TestRenderAsmFileEmitsQuadData(t *testing.T) {
	input := strings.TrimSpace(`
LCPI0_0:
.quad 1
.quad -2

// .globl _load
_load:
VMOVDQA LCPI0_0(SB), Y0
RET
`) + "\n"

	got, err := RenderAsmFile(input)
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	checks := []string{
		"DATA LCPI0_0+0(SB)/8, $1",
		"DATA LCPI0_0+8(SB)/8, $-2",
		"GLOBL LCPI0_0(SB), RODATA|NOPTR, $16",
		"TEXT _load(SB), NOSPLIT|NOFRAME, $0",
		"\tVMOVDQA LCPI0_0(SB), Y0",
	}
	for _, want := range checks {
		if !strings.Contains(got, want) {
			t.Fatalf("output missing %q\n%s", want, got)
		}
	}
	if strings.Contains(got, "TEXT LCPI0_0(SB)") {
		t.Fatalf("data label should not be rendered as TEXT\n%s", got)
	}
}

func TestRenderAsmFileSanitizesELFLocalLabels(t *testing.T) {
	input := strings.TrimSpace(`
foo:
JE .Ldone
.Ldone:
RET
`) + "\n"

	got, err := RenderAsmFile(input)
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	for _, want := range []string{"\tJE Ldone", "Ldone:"} {
		if !strings.Contains(got, want) {
			t.Fatalf("output missing %q\n%s", want, got)
		}
	}
	if strings.Contains(got, ".Ldone") {
		t.Fatalf("ELF local labels should be sanitized\n%s", got)
	}
}
