package codegen

import (
	"strings"
	"testing"
)

func TestRenderAsmFileBuildsCompleteAsmFile(t *testing.T) {
	input := strings.TrimSpace(`
// .globl _add
_add:
LEAL (DI)(SI*1), AX
RET

// .globl _max2
_max2:
CMPL DI, SI
RET
`) + "\n"

	got, err := RenderAsmFile(input)
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	checks := []string{
		"// Code generated by c2go; DO NOT EDIT.",
		"#include \"textflag.h\"",
		"// .globl _add",
		"TEXT _add(SB), NOSPLIT|NOFRAME, $0",
		"\tLEAL (DI)(SI*1), AX",
		"TEXT _max2(SB), NOSPLIT|NOFRAME, $0",
		"\tCMPL DI, SI",
	}
	for _, want := range checks {
		if !strings.Contains(got, want) {
			t.Fatalf("output missing %q\n%s", want, got)
		}
	}
	if strings.Contains(got, "_add:\n") {
		t.Fatalf("function entry label should be replaced by TEXT\n%s", got)
	}
	if strings.Contains(got, "\n\n\n") {
		t.Fatalf("output should not contain repeated blank lines\n%s", got)
	}
}

func TestRenderAsmFileSingleLabelWithoutGlobl(t *testing.T) {
	got, err := RenderAsmFile("main:\nMOVQ SP, BP\nRET\n")
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	if !strings.Contains(got, "TEXT main(SB), NOSPLIT|NOFRAME, $0") {
		t.Fatalf("output missing TEXT header\n%s", got)
	}
	if strings.Contains(got, "main:\n") {
		t.Fatalf("function label should be consumed into TEXT\n%s", got)
	}
}

func TestRenderAsmFileKeepsPreambleCommentsWithNextFunction(t *testing.T) {
	input := strings.TrimSpace(`
// .globl _add
	PCALIGN $16
_add:
RET

// .globl _sub
// .type _sub,@function
_sub:
RET
`) + "\n"

	got, err := RenderAsmFile(input)
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	checks := []string{
		"// .globl _add\n\tPCALIGN $16\nTEXT _add(SB), NOSPLIT|NOFRAME, $0",
		"// .globl _sub\n// .type _sub,@function\nTEXT _sub(SB), NOSPLIT|NOFRAME, $0",
	}
	for _, want := range checks {
		if !strings.Contains(got, want) {
			t.Fatalf("output missing %q\n%s", want, got)
		}
	}
	if strings.Contains(got, "\t// .type _sub,@function") {
		t.Fatalf("next-function preamble comment should not be appended to previous body\n%s", got)
	}
}

func TestRenderAsmFileUsesFrameMarker(t *testing.T) {
	input := strings.TrimSpace(`
foo:
// c2go: frame 8
MOVQ BP, 0(SP)
MOVQ SP, BP
CALL bar(SB)
MOVQ 0(SP), BP
RET
`) + "\n"

	got, err := RenderAsmFile(input)
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	checks := []string{
		"TEXT foo(SB), NOSPLIT, $8-0",
		"\tMOVQ BP, 0(SP)",
		"\tCALL bar(SB)",
		"\tMOVQ 0(SP), BP",
	}
	for _, want := range checks {
		if !strings.Contains(got, want) {
			t.Fatalf("output missing %q\n%s", want, got)
		}
	}
	if strings.Contains(got, "NOFRAME") {
		t.Fatalf("non-zero frame must not use NOFRAME\n%s", got)
	}
	if strings.Contains(got, "c2go: frame") {
		t.Fatalf("frame marker should not be emitted\n%s", got)
	}
}

func TestRenderAsmFileTerminatesText(t *testing.T) {
	got, err := RenderAsmFile("foo:\nMOVQ AX, BX\n")
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	if !strings.Contains(got, "\tMOVQ AX, BX\n\tRET\n") {
		t.Fatalf("unterminated TEXT should get RET\n%s", got)
	}
}

func TestRenderAsmFileKeepsColdLocalBlocksInFunction(t *testing.T) {
	input := strings.TrimSpace(`
foo:
CALL bar(SB)
RET
// .p2align 4,,10
// .p2align 3
Lcold:
JMP foo(SB)
`) + "\n"

	got, err := RenderAsmFile(input)
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	if strings.Contains(got, "TEXT Lcold(SB)") {
		t.Fatalf("local cold block should stay in previous TEXT\n%s", got)
	}
	for _, want := range []string{"TEXT foo(SB)", "\t// .p2align 4,,10", "Lcold:", "\tJMP foo(SB)"} {
		if !strings.Contains(got, want) {
			t.Fatalf("output missing %q\n%s", want, got)
		}
	}
}

func TestRenderAsmFileEmitsQuadData(t *testing.T) {
	input := strings.TrimSpace(`
LCPI0_0:
.byte 7
.short 8
.long 9
.quad 1
.quad -2

// .globl _load
_load:
VMOVDQA LCPI0_0(SB), Y0
RET
`) + "\n"

	got, err := RenderAsmFile(input)
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	checks := []string{
		"DATA LCPI0_0+0(SB)/1, $7",
		"DATA LCPI0_0+1(SB)/2, $8",
		"DATA LCPI0_0+3(SB)/4, $9",
		"DATA LCPI0_0+7(SB)/8, $1",
		"DATA LCPI0_0+15(SB)/8, $-2",
		"GLOBL LCPI0_0(SB), RODATA|NOPTR, $23",
		"TEXT _load(SB), NOSPLIT|NOFRAME, $0",
		"\tVMOVDQA LCPI0_0(SB), Y0",
	}
	for _, want := range checks {
		if !strings.Contains(got, want) {
			t.Fatalf("output missing %q\n%s", want, got)
		}
	}
	if strings.Contains(got, "TEXT LCPI0_0(SB)") {
		t.Fatalf("data label should not be rendered as TEXT\n%s", got)
	}
}

func TestDataDirectiveRejectsInvalidSize(t *testing.T) {
	defer func() {
		if recover() == nil {
			t.Fatal("dataDirective should panic for invalid size")
		}
	}()
	_ = dataDirective(3)
}

func TestRenderAsmFileSanitizesELFLocalLabels(t *testing.T) {
	input := strings.TrimSpace(`
foo:
JE .Ldone
.Ldone:
RET
`) + "\n"

	got, err := RenderAsmFile(input)
	if err != nil {
		t.Fatalf("RenderAsmFile() error = %v", err)
	}
	for _, want := range []string{"\tJE Ldone", "Ldone:"} {
		if !strings.Contains(got, want) {
			t.Fatalf("output missing %q\n%s", want, got)
		}
	}
	if strings.Contains(got, ".Ldone") {
		t.Fatalf("ELF local labels should be sanitized\n%s", got)
	}
}
